name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest

    # Создаем архив с файлами проекта
    - name: Create deployment package
      run: |
        tar -czf deploy.tar.gz \
          docker-compose.yml \
          Dockerfile \
          requirements.txt \
          app.py \
          templates/

    # Сохраняем архив как артефакт (обновленная версия)
    - name: Upload deployment package
      uses: actions/upload-artifact@v3
      with:
        name: deploy-package
        path: deploy.tar.gz
        retention-days: 1

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
    # Скачиваем архив (обновленная версия)
    - name: Download deployment package
      uses: actions/download-artifact@v3
      with:
        name: deploy-package

    # Копируем файлы на сервер и разворачиваем приложение
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          # Установка Docker и Docker Compose (если не установлены)
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y docker.io
          fi

          if ! command -v docker-compose &> /dev/null; then
            echo "Installing Docker Compose..."
            sudo apt-get install -y docker-compose
          fi

          # Подготовка директории
          mkdir -p ~/devops-demo
          cd ~/devops-demo

    # Копируем архив на сервер
    - name: Copy deployment package
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        source: "deploy.tar.gz"
        target: "~/devops-demo"

    # Распаковываем и запускаем
    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd ~/devops-demo
          tar -xzf deploy.tar.gz
          sudo docker-compose down || true
          sudo docker-compose up -d --build
          rm deploy.tar.gz