name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        pip install -r requirements.txt
    
    - name: Test with pytest
      run: |
        pytest

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          # Установка необходимых пакетов (если их нет)
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y docker.io
          fi

          if ! command -v docker-compose &> /dev/null; then
            echo "Installing Docker Compose..."
            sudo apt-get install -y docker-compose
          fi

          # Добавление пользователя в группу docker
          sudo usermod -aG docker $USER

          # Создание директории проекта
          mkdir -p ~/devops-demo
          cd ~/devops-demo

          # Загрузка файлов проекта (без использования git clone)
          wget https://raw.githubusercontent.com/noragami90/devops-demo/main/docker-compose.yml -O docker-compose.yml
          wget https://raw.githubusercontent.com/noragami90/devops-demo/main/Dockerfile -O Dockerfile
          wget https://raw.githubusercontent.com/noragami90/devops-demo/main/requirements.txt -O requirements.txt
          
          # Создание директории для приложения
          mkdir -p app templates
          wget https://raw.githubusercontent.com/noragami90/devops-demo/main/app.py -O app/app.py
          wget https://raw.githubusercontent.com/noragami90/devops-demo/main/templates/index.html -O templates/index.html

          # Перезапуск контейнеров
          sudo docker-compose down || true
          sudo docker-compose up -d