name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        pip install -r requirements.txt
    
    - name: Test with pytest
      run: |
        pytest

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
    - name: Print Debug Info
      run: echo "Starting deployment to ${{ secrets.VPS_HOST }}"

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        debug: true
        script: |
          whoami
          pwd
          cd ~/devops-demo || mkdir -p ~/devops-demo
          if [ ! -d .git ]; then
            git clone https://github.com/noragami90/devops-demo.git .
          else
            git pull origin main
          fi
          docker-compose down || true
          docker-compose up -d